name: mastodonactiontest
on:
  push:
    branches:
      - main
  #workflow_dispatch:
jobs:
  autoupdate-readme:
    runs-on: ubuntu-latest
    name: mastodonactiontest
    environment: myenv
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: mastodonactiontest
        uses: EllieTheYeen/MastodonActionTest
        with:
          email: 42704150+EllieTheYeen@users.noreply.github.com
          instance: https://botsin.space
          blogbase: https://ellietheyeen.github.io/Test
